name: Run Tests

on:
  push:
    branches:
      - master
jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
        make runtest
        make run
    - uses: actions/upload-artifact@v2
      with:
      name: Results
      path: build/Results.csv